# Generated by Django 4.0.3 on 2022-04-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('stor', models.CharField(max_length=100)),
                ('no_item', models.IntegerField()),
            ],
        ),
    ]
