# Generated by Django 4.0.3 on 2022-04-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('duration', models.IntegerField(verbose_name=50)),
                ('units', models.IntegerField(verbose_name=50)),
            ],
        ),
    ]
